paterson_repl_dict = {
    "(N 2ND ST)": '',
    "ALDEN TR": 'ALDEN TERRACE',
    "CV": "",
    "PT ": "",
    "PT.": "",
    "FT.": "",
    "FT": "",
    "FRT": "",
    "FRTS. ": "",
    "RRS": "",
    "FRONT": "",
    "REAR": "",
    "TR CV": "TR",
    "MC BRIDE": "MCBRIDE",
    "BOULDER RUN": "BOULDER RUN ROAD",
    "FT": "",
    "MILL PLOT ": "",
    "RIVER TR": "RIVER TERRACE",
    "DON BOSCO": "SHERWOOD",
    "HOPE": "OXFORD",
    r'\sUNIT\s\d{1,}': "",
    r'-?\s?1/2?': ""
}
