replacement_dict = {
    'KENNEDY': 'JOHN F. KENNEDY',
    'LIBERTY ST.': 'LIBERTY AVE',
    'TONNELE': 'TONNELLE',
    'MC ADOO': 'MCADOO',
    'M.L. KING DRIVE': 'MARTIN LUTHER KING DRIVE',
    'COLUMBUS': 'CHRISTOPHER COLUMBUS',
    'FIRST': '1st',
    'SECOND': '2nd',
    'THIRD': '3rd',
    'FOURTH': '4th',
    'FIFTH': '5th',
    'SIXTH': '6th',
    'SEVENTH': '7th',
    'EIGHTH': '8th',
    'NINETH': '9th',
    'NINTH': '9th',
    'TENTH': '10th',
    'FIFTEENTH': '15th',
    'SIXTEENTH': '16th',
    'MC DOUGALL': 'MCDOUGAL',
    'CARPENTIER': 'CARPENTER',
    'FOX HOUND': 'FOXHOUND',
    'SIEDLER': 'SEIDLER',
    'LIENAU': 'LINEAU',
    '-REAR': '',
    '(REAR)': '',
    '-FRONT': '',
    'HAMPTON CT.': 'HAMPTON COURT',
    r'\(\)': '',
    'VARCK': 'VARICK',
    'THO': '',
    'AVE AVE': 'AVE',
    'TER': 'TR',
    '3633A': '3633',
    '3144A': '3144',
    'SHEARWATR': 'SHEARWATER',
    'PALUSL': "PAUL'S",
    'COURT TR': "CT",
    'EASTVIEW': "E VIEW",
    'M.L. KING DR.': 'MARTIN LUTHER KING DR.',
    ' 1ST FL.': '',
    ' SO.': '',
    ' N.': '',
    'ODGEN': 'OGDEN',
    'PATRSON': 'PATERSON',
    ' 61 COLES': '',
    r'-\d{2,}(.?\d{1}(A)?)?A?\b': '',
    r'-\d{2,}': '',
    r'\s#\d': '',
    'VAN HOUTEN ST.': 'VAN HOUTEN AVE.',
    'MC PHERSON ST.': 'MCPHERSON PL.'
}
